name: MinecartTrains
version: '${project.version}'
main: me.fridtjof.minecarttrains.MinecartTrains
api-version: '1.21'
authors: [ Fridtjof Goes (~Fridtjof_DE) ]
website: https://www.fridtjof.me
depend: [PuddingAPI]
